# Generated by Django 3.1.5 on 2021-01-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
            preserve_default=False,
        ),
    ]
