# Generated by Django 3.1.5 on 2021-01-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_session_sep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='sep',
        ),
    ]
