# Generated by Django 3.1.5 on 2021-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_auto_20210113_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='weekday',
            field=models.IntegerField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')]),
        ),
    ]
