# Generated by Django 3.1.5 on 2021-01-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20210113_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
