# Generated by Django 3.1.5 on 2021-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_auto_20210113_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(blank=True, default=models.CharField(choices=[('Weekly Session', 'Weekly Session'), ('One Day Session', 'One Day Session')], max_length=40), null=True),
        ),
    ]
