# Generated by Django 3.1.5 on 2021-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_auto_20210113_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
