# Generated by Django 3.1.5 on 2021-01-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_auto_20210113_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=256, unique=True),
        ),
    ]
