# Generated by Django 3.1.5 on 2021-01-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20210113_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='doctor',
        ),
    ]
